
all: 
	@echo "Usage: make <target>"


hello-world:
	go build -o $@.out $@.go

packages: 
	go build -o $@.out $@.go

func-multi-results:
	go build -o $@.out $@.go

for:
	go build -o $@.out $@.go

if:
	go build -o $@.out $@.go

switch:
	go build -o $@.out $@.go

defer:
	go build -o $@.out $@.go

methods:
	go build -o $@.out $@.go

interfaces:
	go build -o $@.out $@.go

type-assertions:
	go build -o $@.out $@.go

type-switches:
	go build -o $@.out $@.go

stringers:
	go build -o $@.out $@.go

errors:
	go build -o $@.out $@.go

readers:
	go build -o $@.out $@.go

rot13-reader:
	go build -o $@.out $@.go

images:
	go build -o $@.out $@.go

write-file:
	go build -o $@.out $@.go

read-file:
	go build -o $@.out $@.go

log:
	go build -o $@.out $@.go

main-args:
	go build -o $@.out $@.go

command-line-flags:
	go build -o $@.out $@.go







